baseURL = 'https://myblankspace.netlify.app/'
languageCode = 'en-us'
title = 'Write​_'
theme = 'mytheme'
summaryLength = 20

[params]
	username = "writeblankspace"
	displayName = "the mercurial yapper"
	socialURL = "https://shonk.social/@writeblankspace"

[menus]
	[[menus.main]]
		name = "Home"
		pageRef = "/"
		weight = 10
	[[menus.main]]
		name = "Posts"
		pageRef = "/posts/"
		weight = 20

[pagination]
	pagerSize = 5

[markup.goldmark.renderer]
	unsafe = true
