baseURL = 'https://writeblankspace.netlify.app/'
languageCode = 'en-us'
title = 'Write​_'
theme = 'mytheme'

capitalizeListTitles = false
summaryLength = 30
enableGitInfo = true

[params]
	baseURL = 'writeblankspace.netlify.app'
	username = 'writeblankspace'
	displayName = 'a mercurial mess of random thoughts'
	socialURL = 'https://shonk.social/@writeblankspace'
	gitURL = 'https://github.com/writeblankspace/theblankspace'
	css = 'style.css'

[menus]
	[[menus.main]]
		name = 'Home'
		pageRef = '/'
		weight = 10
	[[menus.main]]
		name = 'Posts'
		pageRef = '/posts/'
		weight = 20
	[[menus.main]]
		name = 'Tags'
		pageRef = '/tags/'
		weight = 30

[frontmatter]
	lastmod = ['lastmod', 'date', 'publishdate', 'pubdate', 'published', ':default']

[pagination]
	pagerSize = 5

[markup.goldmark.renderer]
	unsafe = true

[security]
	enableInlineShortcodes = true
