baseURL = 'https://myblankspace.netlify.app/'
languageCode = 'en-us'
title = 'Write​_'
theme = 'mytheme'
summaryLength = 30

[params]
	username = 'writeblankspace'
	displayName = 'a mercurial mess of random thoughts'
	socialURL = 'https://shonk.social/@writeblankspace'

[menus]
	[[menus.main]]
		name = 'Home'
		pageRef = '/'
		weight = 10
	[[menus.main]]
		name = 'Posts'
		pageRef = '/posts/'
		weight = 20
	[[menus.main]]
		name = 'Tags'
		pageRef = '/tags/'
		weight = 30

[pagination]
	pagerSize = 5

[markup.goldmark.renderer]
	unsafe = true
